### ISSUE TITLE
Counts are incorrect for empty string

### ISSUE THREAD

**Issue by conartist6** [Jadack/VowelsCounterLibrary#1]
Hello yes, I have just discovered the fabulous vowels counter you have published on npm and am using it in my project. My only problem is that when I write the following code I am getting some output I do not expect.

```js
import { VowelsCounter } from 'vowels-counter';

console.log(new VowelsCounter().vowelsCounter(''));
// { A: 4, E: 1, I: 2, O: 0, U: 0 }
```
What I expected was `{ A: 0, E: 0, I: 0, O: 0, U: 0 }`.

**Comment by Jadack** [comment]
Good morning,
First of all I want to thank you for using my library, secondly I would like to be able to validate the implementation you have because through the tests the result I receive is different from the one described in the issue (see attached image).
![image](https://user-images.githubusercontent.com/29097604/133785740-3a87085b-5072-48ff-a01e-c9c8f3664f28.png)

**Comment by Jadack** [comment]
@conartist6 The issue has been solved in the new version, after making another more complete implementation I noticed that the value of what was previously checked was saved globally and therefore when repeating the function it kept the old values and add the result = newValue + oldValue.
This issue has already been corrected, thank you very much for the review.

**Comment by conartist6** [comment]
Ah, ok! I must admit that I'm not actually using your package, I'm just reading the code. I happened to see it in the "recent packages" feed on NPM, and actually I think I just misread the code. Thanks for putting out the improved version though -- you're on your way to becoming a real package maintainer!

I don't know if you actually want to keep working on this, but if you do there's still some improvements to make. While `inputValidator` doesn't quite do what I thought (count the vowels in `Entrada Invalida`) that's actually because it doesn't do anything at all. Anway, best of luck in your studies!

**Comment by Jadack** [comment]
Yes, it has many improvements that I must make.
The code and the package release were for an university homework, however I feel motivated to keep improving it.
Thanks for the comments and advice!!
